# Generated by Django 5.2.3 on 2025-07-09 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='image_url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='price_per_day',
            field=models.DecimalField(decimal_places=2, default=25.0, max_digits=10),
        ),
    ]
