# Generated by Django 5.2.3 on 2025-07-09 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_vehicle_image_url_vehicle_price_per_day'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='fuel_type',
            field=models.CharField(choices=[('petrol', 'Petrol'), ('diesel', 'Diesel'), ('electric', 'Electric'), ('hybrid', 'Hybrid'), ('manual', 'Manual')], default='petrol', max_length=10),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='seats',
            field=models.PositiveIntegerField(default=5, help_text='Number of seats (for cars)'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='transmission',
            field=models.CharField(choices=[('automatic', 'Automatic'), ('manual', 'Manual'), ('none', 'None')], default='automatic', max_length=10),
        ),
    ]
