# Generated by Django 5.2.3 on 2025-07-11 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_vehicle_fuel_type_vehicle_seats_vehicle_transmission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='status',
            field=models.CharField(choices=[('pending_payment', 'Pending Payment'), ('payment_failed', 'Payment Failed'), ('active', 'Active'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending_payment', max_length=20),
        ),
    ]
